#! /bin/bash

if [ $# -eq 0 ]
then
    echo "Usage: clone [<user:srafi1>] <repo>"
elif [ $# -eq 1 ]
then
    git clone git@github.com:srafi1/$1
elif [ $# -eq 2 ]
then
    git clone git@github.com:$1/$2
else
    git clone git@github.com:$1/$2 $3
fi
