#! /bin/bash

touch app.py
mkdir templates
mkdir util
mkdir data
mkdir static
touch templates/index.html
touch util/__init__.py

echo "Is this a hw?[y/n]: "
read -s -n 1 hw
if [ $hw = "y" ]
then
    echo "Enter hw number: "
    read hwnum
    echo "Enter summary: "
    read summary

    echo "# Shakil Rafi" >> app.py
    echo "# SoftDev1 pd7" >> app.py
    echo "# HW$hwnum -- $summary" >> app.py
    echo "# $(date +%Y-%m-%d)" >> app.py
fi
