#! /bin/bash

for d in *
do
    if [ -d $d ]
    then
        cd $d
        if [ -d ".git" ]
        then
            echo " "
            echo "-----Pulling from $d-----"
            git pull
        fi
        if [ -f ".git" ]
        then
            echo " "
            echo "-----Updating submodule $d-----"
            git pull origin master
        fi
        cd ..
    fi
done

