#! /bin/bash

if [ -z $1 ]
then
    msg="Automatic commit message"
else
    msg="$1"
fi

if [ -d ".git" ]
then
    git add . -A
    git commit -m "$msg"
    git push
else
    echo "This is not a git dir"
fi
