#! /bin/bash

# add all files, commit to git, and push

if [ $# -eq 0 ]
then
    msg="Automatic commit message"
else
    msg="$@"
fi

if [ -d ".git" ]
then
    git add . -A
    git commit -m "$msg"
    git push
else
    echo "This is not a git dir"
fi
