#! /bin/python

# print average of all inputs

import argparse, statistics

parser = argparse.ArgumentParser(description='Calculate average of inputs')
parser.add_argument('nums', type=float, nargs='+',
        help='Numbers to calculate average of')
parser.add_argument('-v', '--verbose', action='store_true',
        help='Output sum and number of inputs')

args = parser.parse_args()

if args.verbose:
    print('total: %f' % sum(args.nums))
    print('num: %d' % len(args.nums))
    print('avg: %f' % statistics.mean(args.nums))
else:
    print(statistics.mean(args.nums))
