#! /bin/python

# print average of all inputs

import sys

total = 0

for i in sys.argv[1:]:
    total += float(i)

print('total: %f' % total)
print('num: %d' % (len(sys.argv) - 1))
print('avg: %f' % (total / (len(sys.argv) - 1)))
