#! /bin/bash

# toggle connection to paired bluetooth devices (meant for headphones)
# add "headphones" to the name for the devices using Blueman

rfkill unblock bluetooth

bt_headphones() {
    bluetoothctl paired-devices |
        grep -i headphones |
        cut -f 2 -d " "
}

anyconnected=no
devices=$(bt_headphones)
for d in $devices; do
    connected=$(bluetoothctl info $d |
        grep Connected |
        cut -f 2 -d " ")
    if [ $connected = yes ]; then
        anyconnected=yes
    fi
done

if [ $anyconnected = yes ];then
    echo "A bluetooth connection exists"
    bluetoothctl disconnect
else
    echo "No bluetooth connections exists"
    for i in $(bt_headphones)
    do
        bluetoothctl connect $i
    done
fi
