#! /bin/bash

# lock using i3 with a blurred screenshot of the current screen

ICON=$HOME/.config/lock.png
rm -f /tmp/screen.png
scrot /tmp/screen.png
TMPBG=/tmp/screen.png
convert $TMPBG -scale 10% -scale 1000% $TMPBG
convert $TMPBG $ICON -gravity center -composite -matte $TMPBG
i3lock -u -i $TMPBG
